// <auto-generated />
namespace SoCrm.Infrastructure.Persistence.EntityFramework.Provider.Migrations.Security
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class InitialSecurityModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialSecurityModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201303141526567_InitialSecurityModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
