//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoCrm.Services.Logging.Provider.LogEventPersistence {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogEventPersistence.IPersistenceServiceOf_LogEvent")]
    public interface IPersistenceServiceOf_LogEvent {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersistenceServiceOf_LogEvent/Save", ReplyAction="http://tempuri.org/IPersistenceServiceOf_LogEvent/SaveResponse")]
        System.Guid Save(SoCrm.Services.Logging.Contracts.LogEvent entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersistenceServiceOf_LogEvent/Save", ReplyAction="http://tempuri.org/IPersistenceServiceOf_LogEvent/SaveResponse")]
        System.Threading.Tasks.Task<System.Guid> SaveAsync(SoCrm.Services.Logging.Contracts.LogEvent entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersistenceServiceOf_LogEvent/Get", ReplyAction="http://tempuri.org/IPersistenceServiceOf_LogEvent/GetResponse")]
        SoCrm.Services.Logging.Contracts.LogEvent Get(System.Guid objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersistenceServiceOf_LogEvent/Get", ReplyAction="http://tempuri.org/IPersistenceServiceOf_LogEvent/GetResponse")]
        System.Threading.Tasks.Task<SoCrm.Services.Logging.Contracts.LogEvent> GetAsync(System.Guid objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersistenceServiceOf_LogEvent/GetAll", ReplyAction="http://tempuri.org/IPersistenceServiceOf_LogEvent/GetAllResponse")]
        SoCrm.Services.Logging.Contracts.LogEvent[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersistenceServiceOf_LogEvent/GetAll", ReplyAction="http://tempuri.org/IPersistenceServiceOf_LogEvent/GetAllResponse")]
        System.Threading.Tasks.Task<SoCrm.Services.Logging.Contracts.LogEvent[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersistenceServiceOf_LogEvent/Remove", ReplyAction="http://tempuri.org/IPersistenceServiceOf_LogEvent/RemoveResponse")]
        void Remove(SoCrm.Services.Logging.Contracts.LogEvent entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersistenceServiceOf_LogEvent/Remove", ReplyAction="http://tempuri.org/IPersistenceServiceOf_LogEvent/RemoveResponse")]
        System.Threading.Tasks.Task RemoveAsync(SoCrm.Services.Logging.Contracts.LogEvent entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersistenceServiceOf_LogEventChannel : SoCrm.Services.Logging.Provider.LogEventPersistence.IPersistenceServiceOf_LogEvent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersistenceServiceOf_LogEventClient : System.ServiceModel.ClientBase<SoCrm.Services.Logging.Provider.LogEventPersistence.IPersistenceServiceOf_LogEvent>, SoCrm.Services.Logging.Provider.LogEventPersistence.IPersistenceServiceOf_LogEvent {
        
        public PersistenceServiceOf_LogEventClient() {
        }
        
        public PersistenceServiceOf_LogEventClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersistenceServiceOf_LogEventClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersistenceServiceOf_LogEventClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersistenceServiceOf_LogEventClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid Save(SoCrm.Services.Logging.Contracts.LogEvent entity) {
            return base.Channel.Save(entity);
        }
        
        public System.Threading.Tasks.Task<System.Guid> SaveAsync(SoCrm.Services.Logging.Contracts.LogEvent entity) {
            return base.Channel.SaveAsync(entity);
        }
        
        public SoCrm.Services.Logging.Contracts.LogEvent Get(System.Guid objectId) {
            return base.Channel.Get(objectId);
        }
        
        public System.Threading.Tasks.Task<SoCrm.Services.Logging.Contracts.LogEvent> GetAsync(System.Guid objectId) {
            return base.Channel.GetAsync(objectId);
        }
        
        public SoCrm.Services.Logging.Contracts.LogEvent[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<SoCrm.Services.Logging.Contracts.LogEvent[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public void Remove(SoCrm.Services.Logging.Contracts.LogEvent entity) {
            base.Channel.Remove(entity);
        }
        
        public System.Threading.Tasks.Task RemoveAsync(SoCrm.Services.Logging.Contracts.LogEvent entity) {
            return base.Channel.RemoveAsync(entity);
        }
    }
}
