//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoCrm.Presentation.Security.Security {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Security.ISecurityService")]
    public interface ISecurityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/GetAllUsers", ReplyAction="http://tempuri.org/ISecurityService/GetAllUsersResponse")]
        System.Collections.Generic.List<SoCrm.Services.Security.Contracts.User> GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/GetAllRoles", ReplyAction="http://tempuri.org/ISecurityService/GetAllRolesResponse")]
        System.Collections.Generic.List<SoCrm.Services.Security.Contracts.Role> GetAllRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/GetUsersByRole", ReplyAction="http://tempuri.org/ISecurityService/GetUsersByRoleResponse")]
        System.Collections.Generic.List<SoCrm.Services.Security.Contracts.User> GetUsersByRole(SoCrm.Services.Security.Contracts.Role role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/GetUsersByRoleAndUserName", ReplyAction="http://tempuri.org/ISecurityService/GetUsersByRoleAndUserNameResponse")]
        System.Collections.Generic.List<SoCrm.Services.Security.Contracts.User> GetUsersByRoleAndUserName(SoCrm.Services.Security.Contracts.Role role, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/ValidateCredentials", ReplyAction="http://tempuri.org/ISecurityService/ValidateCredentialsResponse")]
        bool ValidateCredentials(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/GetUserByCredentials", ReplyAction="http://tempuri.org/ISecurityService/GetUserByCredentialsResponse")]
        SoCrm.Services.Security.Contracts.User GetUserByCredentials(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/GetUserByObjectId", ReplyAction="http://tempuri.org/ISecurityService/GetUserByObjectIdResponse")]
        SoCrm.Services.Security.Contracts.User GetUserByObjectId(System.Guid objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/SetPassword", ReplyAction="http://tempuri.org/ISecurityService/SetPasswordResponse")]
        void SetPassword(SoCrm.Services.Security.Contracts.User user, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/CreateUser", ReplyAction="http://tempuri.org/ISecurityService/CreateUserResponse")]
        SoCrm.Services.Security.Contracts.User CreateUser(string userName, string password, SoCrm.Services.Security.Contracts.Role role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/DeleteUser", ReplyAction="http://tempuri.org/ISecurityService/DeleteUserResponse")]
        void DeleteUser(SoCrm.Services.Security.Contracts.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecurityServiceChannel : SoCrm.Presentation.Security.Security.ISecurityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecurityServiceClient : System.ServiceModel.ClientBase<SoCrm.Presentation.Security.Security.ISecurityService>, SoCrm.Presentation.Security.Security.ISecurityService {
        
        public SecurityServiceClient() {
        }
        
        public SecurityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecurityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<SoCrm.Services.Security.Contracts.User> GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Collections.Generic.List<SoCrm.Services.Security.Contracts.Role> GetAllRoles() {
            return base.Channel.GetAllRoles();
        }
        
        public System.Collections.Generic.List<SoCrm.Services.Security.Contracts.User> GetUsersByRole(SoCrm.Services.Security.Contracts.Role role) {
            return base.Channel.GetUsersByRole(role);
        }
        
        public System.Collections.Generic.List<SoCrm.Services.Security.Contracts.User> GetUsersByRoleAndUserName(SoCrm.Services.Security.Contracts.Role role, string userName) {
            return base.Channel.GetUsersByRoleAndUserName(role, userName);
        }
        
        public bool ValidateCredentials(string userName, string password) {
            return base.Channel.ValidateCredentials(userName, password);
        }
        
        public SoCrm.Services.Security.Contracts.User GetUserByCredentials(string userName, string password) {
            return base.Channel.GetUserByCredentials(userName, password);
        }
        
        public SoCrm.Services.Security.Contracts.User GetUserByObjectId(System.Guid objectId) {
            return base.Channel.GetUserByObjectId(objectId);
        }
        
        public void SetPassword(SoCrm.Services.Security.Contracts.User user, string oldPassword, string newPassword) {
            base.Channel.SetPassword(user, oldPassword, newPassword);
        }
        
        public SoCrm.Services.Security.Contracts.User CreateUser(string userName, string password, SoCrm.Services.Security.Contracts.Role role) {
            return base.Channel.CreateUser(userName, password, role);
        }
        
        public void DeleteUser(SoCrm.Services.Security.Contracts.User user) {
            base.Channel.DeleteUser(user);
        }
    }
}
