// <auto-generated />
namespace SoCrm.Infrastructure.Persistence.EntityFramework.Migrations.Customer
{
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    public sealed partial class UsingCollections : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsingCollections));
        
        string IMigrationMetadata.Id
        {
            get { return "201303161702337_UsingCollections"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return this.Resources.GetString("Target"); }
        }
    }
}
