// <auto-generated />
namespace SoCrm.Infrastructure.Persistence.EntityFramework.Migrations.Contact
{
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    public sealed partial class InitialContactModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialContactModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201303141815106_InitialContactModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return this.Resources.GetString("Target"); }
        }
    }
}
