// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace SoCrm.Tests.AcceptanceTests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// EnterCredentials - Use 'EnterCredentialsParams' to pass parameters into this method.
        /// </summary>
        public void EnterCredentials()
        {
            #region Variable Declarations
            WpfEdit uIItemEdit = this.UIServiceOrientedCRMWindow.UIItemCustom.UIAuthenticateCredentiGroup.UIUsernameText.UIItemEdit;
            WpfEdit uIItemEdit1 = this.UIServiceOrientedCRMWindow.UIItemCustom.UIAuthenticateCredentiGroup.UIPasswordText.UIItemEdit;
            #endregion

            // Type 'Florian' in first text box next to 'Username' label
            uIItemEdit.Text = this.EnterCredentialsParams.UIItemEditText;

            // Click first text box next to 'Password' label
            Mouse.Click(uIItemEdit1, new Point(233, 7));

            // Type '********' in first text box next to 'Password' label
            Keyboard.SendKeys(uIItemEdit1, this.EnterCredentialsParams.UIItemEditSendKeys, true);
        }
        
        /// <summary>
        /// LogOn
        /// </summary>
        public void LogOn()
        {
            #region Variable Declarations
            WpfButton uILogOnButton = this.UIServiceOrientedCRMWindow.UIItemCustom.UIAuthenticateCredentiGroup.UILogOnButton;
            #endregion

            // Click 'Log On' button
            Mouse.Click(uILogOnButton, new Point(109, 14));
        }
        
        /// <summary>
        /// OpenAuthentication
        /// </summary>
        public void OpenAuthentication()
        {
            #region Variable Declarations
            WpfButton uIItemButton = this.UIServiceOrientedCRMWindow.UIItemToolBar.UIToolBarThumbIndicator.UIItemButton;
            #endregion

            // Click first button next to 'ToolBarThumb' Indicator
            Mouse.Click(uIItemButton, new Point(7, 16));
        }
        
        #region Properties
        public virtual EnterCredentialsParams EnterCredentialsParams
        {
            get
            {
                if ((this.mEnterCredentialsParams == null))
                {
                    this.mEnterCredentialsParams = new EnterCredentialsParams();
                }
                return this.mEnterCredentialsParams;
            }
        }
        
        public UIServiceOrientedCRMWindow UIServiceOrientedCRMWindow
        {
            get
            {
                if ((this.mUIServiceOrientedCRMWindow == null))
                {
                    this.mUIServiceOrientedCRMWindow = new UIServiceOrientedCRMWindow();
                }
                return this.mUIServiceOrientedCRMWindow;
            }
        }
        
        public UIDebugWindow UIDebugWindow
        {
            get
            {
                if ((this.mUIDebugWindow == null))
                {
                    this.mUIDebugWindow = new UIDebugWindow();
                }
                return this.mUIDebugWindow;
            }
        }
        #endregion
        
        #region Fields
        private EnterCredentialsParams mEnterCredentialsParams;
        
        private UIServiceOrientedCRMWindow mUIServiceOrientedCRMWindow;
        
        private UIDebugWindow mUIDebugWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'EnterCredentials'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class EnterCredentialsParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Florian' in first text box next to 'Username' label
        /// </summary>
        public string UIItemEditText = "Florian";
        
        /// <summary>
        /// Type '********' in first text box next to 'Password' label
        /// </summary>
        public string UIItemEditSendKeys = "hcUvlo5grpdp3sPFgUcb1RMmMzXVyf+H";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIServiceOrientedCRMWindow : WpfWindow
    {
        
        public UIServiceOrientedCRMWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Service Oriented CRM";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Service Oriented CRM");
            #endregion
        }
        
        #region Properties
        public UIItemToolBar UIItemToolBar
        {
            get
            {
                if ((this.mUIItemToolBar == null))
                {
                    this.mUIItemToolBar = new UIItemToolBar(this);
                }
                return this.mUIItemToolBar;
            }
        }
        
        public UIItemCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new UIItemCustom(this);
                }
                return this.mUIItemCustom;
            }
        }
        
        public UISoCrmPresentationSecPane UISoCrmPresentationSecPane
        {
            get
            {
                if ((this.mUISoCrmPresentationSecPane == null))
                {
                    this.mUISoCrmPresentationSecPane = new UISoCrmPresentationSecPane(this);
                }
                return this.mUISoCrmPresentationSecPane;
            }
        }
        
        public UIItemCustom1 UIItemCustom1
        {
            get
            {
                if ((this.mUIItemCustom1 == null))
                {
                    this.mUIItemCustom1 = new UIItemCustom1(this);
                }
                return this.mUIItemCustom1;
            }
        }
        
        public UIItemCustom2 UIItemCustom2
        {
            get
            {
                if ((this.mUIItemCustom2 == null))
                {
                    this.mUIItemCustom2 = new UIItemCustom2(this);
                }
                return this.mUIItemCustom2;
            }
        }
        #endregion
        
        #region Fields
        private UIItemToolBar mUIItemToolBar;
        
        private UIItemCustom mUIItemCustom;
        
        private UISoCrmPresentationSecPane mUISoCrmPresentationSecPane;
        
        private UIItemCustom1 mUIItemCustom1;
        
        private UIItemCustom2 mUIItemCustom2;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIItemToolBar : WpfToolBar
    {
        
        public UIItemToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Service Oriented CRM");
            #endregion
        }
        
        #region Properties
        public UIToolBarThumbIndicator UIToolBarThumbIndicator
        {
            get
            {
                if ((this.mUIToolBarThumbIndicator == null))
                {
                    this.mUIToolBarThumbIndicator = new UIToolBarThumbIndicator(this);
                }
                return this.mUIToolBarThumbIndicator;
            }
        }
        #endregion
        
        #region Fields
        private UIToolBarThumbIndicator mUIToolBarThumbIndicator;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIToolBarThumbIndicator : WpfControl
    {
        
        public UIToolBarThumbIndicator(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Indicator";
            this.SearchProperties["AutomationId"] = "ToolBarThumb";
            this.WindowTitles.Add("Service Oriented CRM");
            #endregion
        }
        
        #region Properties
        public WpfButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIItemButton.WindowTitles.Add("Service Oriented CRM");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIItemButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIItemCustom : WpfCustom
    {
        
        public UIItemCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "Uia.AuthenticationView";
            this.WindowTitles.Add("Service Oriented CRM");
            #endregion
        }
        
        #region Properties
        public UIAuthenticateCredentiGroup UIAuthenticateCredentiGroup
        {
            get
            {
                if ((this.mUIAuthenticateCredentiGroup == null))
                {
                    this.mUIAuthenticateCredentiGroup = new UIAuthenticateCredentiGroup(this);
                }
                return this.mUIAuthenticateCredentiGroup;
            }
        }
        #endregion
        
        #region Fields
        private UIAuthenticateCredentiGroup mUIAuthenticateCredentiGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIAuthenticateCredentiGroup : WpfGroup
    {
        
        public UIAuthenticateCredentiGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfGroup.PropertyNames.Name] = "Authenticate Credentials";
            this.WindowTitles.Add("Service Oriented CRM");
            #endregion
        }
        
        #region Properties
        public UIUsernameText UIUsernameText
        {
            get
            {
                if ((this.mUIUsernameText == null))
                {
                    this.mUIUsernameText = new UIUsernameText(this);
                }
                return this.mUIUsernameText;
            }
        }
        
        public UIPasswordText UIPasswordText
        {
            get
            {
                if ((this.mUIPasswordText == null))
                {
                    this.mUIPasswordText = new UIPasswordText(this);
                }
                return this.mUIPasswordText;
            }
        }
        
        public WpfButton UILogOnButton
        {
            get
            {
                if ((this.mUILogOnButton == null))
                {
                    this.mUILogOnButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUILogOnButton.SearchProperties[WpfButton.PropertyNames.Name] = "Log On";
                    this.mUILogOnButton.WindowTitles.Add("Service Oriented CRM");
                    #endregion
                }
                return this.mUILogOnButton;
            }
        }
        #endregion
        
        #region Fields
        private UIUsernameText mUIUsernameText;
        
        private UIPasswordText mUIPasswordText;
        
        private WpfButton mUILogOnButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIUsernameText : WpfText
    {
        
        public UIUsernameText(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfText.PropertyNames.Name] = "Username";
            this.WindowTitles.Add("Service Oriented CRM");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIItemEdit.WindowTitles.Add("Service Oriented CRM");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIPasswordText : WpfText
    {
        
        public UIPasswordText(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfText.PropertyNames.Name] = "Password";
            this.WindowTitles.Add("Service Oriented CRM");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIItemEdit.WindowTitles.Add("Service Oriented CRM");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UISoCrmPresentationSecPane : WpfPane
    {
        
        public UISoCrmPresentationSecPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfPane.PropertyNames.ClassName] = "Uia.ScrollViewer";
            this.SearchProperties[WpfPane.PropertyNames.Name] = "SoCrm.Presentation.Security.UserList.UserListViewModel";
            this.WindowTitles.Add("Service Oriented CRM");
            #endregion
        }
        
        #region Properties
        public WpfGroup UISearchUsersGroup
        {
            get
            {
                if ((this.mUISearchUsersGroup == null))
                {
                    this.mUISearchUsersGroup = new WpfGroup(this);
                    #region Search Criteria
                    this.mUISearchUsersGroup.SearchProperties[WpfGroup.PropertyNames.Name] = "Search Users";
                    this.mUISearchUsersGroup.WindowTitles.Add("Service Oriented CRM");
                    #endregion
                }
                return this.mUISearchUsersGroup;
            }
        }
        #endregion
        
        #region Fields
        private WpfGroup mUISearchUsersGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIItemCustom1 : WpfCustom
    {
        
        public UIItemCustom1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "Uia.UserListView";
            this.WindowTitles.Add("Service Oriented CRM");
            #endregion
        }
        
        #region Properties
        public UISearchUsersGroup UISearchUsersGroup
        {
            get
            {
                if ((this.mUISearchUsersGroup == null))
                {
                    this.mUISearchUsersGroup = new UISearchUsersGroup(this);
                }
                return this.mUISearchUsersGroup;
            }
        }
        #endregion
        
        #region Fields
        private UISearchUsersGroup mUISearchUsersGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UISearchUsersGroup : WpfGroup
    {
        
        public UISearchUsersGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfGroup.PropertyNames.Name] = "Search Users";
            this.WindowTitles.Add("Service Oriented CRM");
            #endregion
        }
        
        #region Properties
        public UIUsernameText1 UIUsernameText
        {
            get
            {
                if ((this.mUIUsernameText == null))
                {
                    this.mUIUsernameText = new UIUsernameText1(this);
                }
                return this.mUIUsernameText;
            }
        }
        #endregion
        
        #region Fields
        private UIUsernameText1 mUIUsernameText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIUsernameText1 : WpfText
    {
        
        public UIUsernameText1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfText.PropertyNames.Name] = "Username";
            this.WindowTitles.Add("Service Oriented CRM");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIItemEdit.WindowTitles.Add("Service Oriented CRM");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIItemCustom2 : WpfCustom
    {
        
        public UIItemCustom2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "Uia.UserListView";
            this.WindowTitles.Add("Service Oriented CRM");
            #endregion
        }
        
        #region Properties
        public UISearchUsersGroup1 UISearchUsersGroup
        {
            get
            {
                if ((this.mUISearchUsersGroup == null))
                {
                    this.mUISearchUsersGroup = new UISearchUsersGroup1(this);
                }
                return this.mUISearchUsersGroup;
            }
        }
        #endregion
        
        #region Fields
        private UISearchUsersGroup1 mUISearchUsersGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UISearchUsersGroup1 : WpfGroup
    {
        
        public UISearchUsersGroup1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfGroup.PropertyNames.Name] = "Search Users";
            this.WindowTitles.Add("Service Oriented CRM");
            #endregion
        }
        
        #region Properties
        public UIUsernameText2 UIUsernameText
        {
            get
            {
                if ((this.mUIUsernameText == null))
                {
                    this.mUIUsernameText = new UIUsernameText2(this);
                }
                return this.mUIUsernameText;
            }
        }
        #endregion
        
        #region Fields
        private UIUsernameText2 mUIUsernameText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIUsernameText2 : WpfText
    {
        
        public UIUsernameText2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfText.PropertyNames.Name] = "Username";
            this.WindowTitles.Add("Service Oriented CRM");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIItemEdit.WindowTitles.Add("Service Oriented CRM");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIDebugWindow : WinWindow
    {
        
        public UIDebugWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Debug";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "CabinetWClass";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Items View";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public UISoCrmPresentationAppListItem UISoCrmPresentationAppListItem
        {
            get
            {
                if ((this.mUISoCrmPresentationAppListItem == null))
                {
                    this.mUISoCrmPresentationAppListItem = new UISoCrmPresentationAppListItem(this);
                }
                return this.mUISoCrmPresentationAppListItem;
            }
        }
        #endregion
        
        #region Fields
        private UISoCrmPresentationAppListItem mUISoCrmPresentationAppListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UISoCrmPresentationAppListItem : WinListItem
    {
        
        public UISoCrmPresentationAppListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinListItem.PropertyNames.Name] = "SoCrm.Presentation.App.exe";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("Debug");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
}
