// <auto-generated />
namespace SoCrm.Infrastructure.Persistence.EntityFramework.Provider.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class LogEvent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LogEvent));
        
        string IMigrationMetadata.Id
        {
            get { return "201303132001381_LogEvent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
