//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoCrm.Services.Customers.Provider.PhoneNumberPersistence {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PhoneNumberPersistence.IPersistenceServiceOf_PhoneNumber")]
    public interface IPersistenceServiceOf_PhoneNumber {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersistenceServiceOf_PhoneNumber/Save", ReplyAction="http://tempuri.org/IPersistenceServiceOf_PhoneNumber/SaveResponse")]
        void Save(SoCrm.Services.Customers.Contracts.PhoneNumber entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersistenceServiceOf_PhoneNumber/Save", ReplyAction="http://tempuri.org/IPersistenceServiceOf_PhoneNumber/SaveResponse")]
        System.Threading.Tasks.Task SaveAsync(SoCrm.Services.Customers.Contracts.PhoneNumber entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersistenceServiceOf_PhoneNumber/Get", ReplyAction="http://tempuri.org/IPersistenceServiceOf_PhoneNumber/GetResponse")]
        SoCrm.Services.Customers.Contracts.PhoneNumber Get(System.Guid objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersistenceServiceOf_PhoneNumber/Get", ReplyAction="http://tempuri.org/IPersistenceServiceOf_PhoneNumber/GetResponse")]
        System.Threading.Tasks.Task<SoCrm.Services.Customers.Contracts.PhoneNumber> GetAsync(System.Guid objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersistenceServiceOf_PhoneNumber/GetAll", ReplyAction="http://tempuri.org/IPersistenceServiceOf_PhoneNumber/GetAllResponse")]
        SoCrm.Services.Customers.Contracts.PhoneNumber[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersistenceServiceOf_PhoneNumber/GetAll", ReplyAction="http://tempuri.org/IPersistenceServiceOf_PhoneNumber/GetAllResponse")]
        System.Threading.Tasks.Task<SoCrm.Services.Customers.Contracts.PhoneNumber[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersistenceServiceOf_PhoneNumber/Remove", ReplyAction="http://tempuri.org/IPersistenceServiceOf_PhoneNumber/RemoveResponse")]
        void Remove(SoCrm.Services.Customers.Contracts.PhoneNumber entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersistenceServiceOf_PhoneNumber/Remove", ReplyAction="http://tempuri.org/IPersistenceServiceOf_PhoneNumber/RemoveResponse")]
        System.Threading.Tasks.Task RemoveAsync(SoCrm.Services.Customers.Contracts.PhoneNumber entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersistenceServiceOf_PhoneNumberChannel : SoCrm.Services.Customers.Provider.PhoneNumberPersistence.IPersistenceServiceOf_PhoneNumber, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersistenceServiceOf_PhoneNumberClient : System.ServiceModel.ClientBase<SoCrm.Services.Customers.Provider.PhoneNumberPersistence.IPersistenceServiceOf_PhoneNumber>, SoCrm.Services.Customers.Provider.PhoneNumberPersistence.IPersistenceServiceOf_PhoneNumber {
        
        public PersistenceServiceOf_PhoneNumberClient() {
        }
        
        public PersistenceServiceOf_PhoneNumberClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersistenceServiceOf_PhoneNumberClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersistenceServiceOf_PhoneNumberClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersistenceServiceOf_PhoneNumberClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Save(SoCrm.Services.Customers.Contracts.PhoneNumber entity) {
            base.Channel.Save(entity);
        }
        
        public System.Threading.Tasks.Task SaveAsync(SoCrm.Services.Customers.Contracts.PhoneNumber entity) {
            return base.Channel.SaveAsync(entity);
        }
        
        public SoCrm.Services.Customers.Contracts.PhoneNumber Get(System.Guid objectId) {
            return base.Channel.Get(objectId);
        }
        
        public System.Threading.Tasks.Task<SoCrm.Services.Customers.Contracts.PhoneNumber> GetAsync(System.Guid objectId) {
            return base.Channel.GetAsync(objectId);
        }
        
        public SoCrm.Services.Customers.Contracts.PhoneNumber[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<SoCrm.Services.Customers.Contracts.PhoneNumber[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public void Remove(SoCrm.Services.Customers.Contracts.PhoneNumber entity) {
            base.Channel.Remove(entity);
        }
        
        public System.Threading.Tasks.Task RemoveAsync(SoCrm.Services.Customers.Contracts.PhoneNumber entity) {
            return base.Channel.RemoveAsync(entity);
        }
    }
}
