// <auto-generated />
namespace SoCrm.Infrastructure.Persistence.EntityFramework.Migrations.Logging
{
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    public sealed partial class InitialLoggingModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialLoggingModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201303141427102_InitialLoggingModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return this.Resources.GetString("Target"); }
        }
    }
}
