//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoCrm.Presentation.Customers.Customer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Customer.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAllPersons", ReplyAction="http://tempuri.org/ICustomerService/GetAllPersonsResponse")]
        System.Collections.Generic.List<SoCrm.Services.Customers.Contracts.Person> GetAllPersons();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAllCompanies", ReplyAction="http://tempuri.org/ICustomerService/GetAllCompaniesResponse")]
        System.Collections.Generic.List<SoCrm.Services.Customers.Contracts.Company> GetAllCompanies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAllCountries", ReplyAction="http://tempuri.org/ICustomerService/GetAllCountriesResponse")]
        System.Collections.Generic.List<string> GetAllCountries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAllEMailAddresses", ReplyAction="http://tempuri.org/ICustomerService/GetAllEMailAddressesResponse")]
        System.Collections.Generic.List<SoCrm.Services.Customers.Contracts.EMailAddress> GetAllEMailAddresses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetContactTypes", ReplyAction="http://tempuri.org/ICustomerService/GetContactTypesResponse")]
        System.Collections.Generic.List<SoCrm.Services.Customers.Contracts.ContactType> GetContactTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAllPhoneNumbers", ReplyAction="http://tempuri.org/ICustomerService/GetAllPhoneNumbersResponse")]
        System.Collections.Generic.List<SoCrm.Services.Customers.Contracts.PhoneNumber> GetAllPhoneNumbers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetPersonByObjectId", ReplyAction="http://tempuri.org/ICustomerService/GetPersonByObjectIdResponse")]
        SoCrm.Services.Customers.Contracts.Person GetPersonByObjectId(System.Guid objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetPersonsByNameAndCompany", ReplyAction="http://tempuri.org/ICustomerService/GetPersonsByNameAndCompanyResponse")]
        System.Collections.Generic.List<SoCrm.Services.Customers.Contracts.Person> GetPersonsByNameAndCompany(string personName, string companyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCompaniesByNameAndCountry", ReplyAction="http://tempuri.org/ICustomerService/GetCompaniesByNameAndCountryResponse")]
        System.Collections.Generic.List<SoCrm.Services.Customers.Contracts.Company> GetCompaniesByNameAndCountry(string name, string counrty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCompanyByObjectId", ReplyAction="http://tempuri.org/ICustomerService/GetCompanyByObjectIdResponse")]
        SoCrm.Services.Customers.Contracts.Company GetCompanyByObjectId(System.Guid objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/CreatePhoneNumber", ReplyAction="http://tempuri.org/ICustomerService/CreatePhoneNumberResponse")]
        SoCrm.Services.Customers.Contracts.PhoneNumber CreatePhoneNumber(string phoneNumber, SoCrm.Services.Customers.Contracts.ContactType contactType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/CreateEmailAddress", ReplyAction="http://tempuri.org/ICustomerService/CreateEmailAddressResponse")]
        SoCrm.Services.Customers.Contracts.EMailAddress CreateEmailAddress(string emailAddress, SoCrm.Services.Customers.Contracts.ContactType contactType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/CreateCompany", ReplyAction="http://tempuri.org/ICustomerService/CreateCompanyResponse")]
        SoCrm.Services.Customers.Contracts.Company CreateCompany(string name, string addressLine, string zipCode, string city, string country, string website);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/CreatePerson", ReplyAction="http://tempuri.org/ICustomerService/CreatePersonResponse")]
        SoCrm.Services.Customers.Contracts.Person CreatePerson(string firstName, string lastName, SoCrm.Services.Customers.Contracts.Company employer, string addressLine, string zipCode, string city, string country, System.Collections.Generic.List<SoCrm.Services.Customers.Contracts.PhoneNumber> phoneNumbers, System.Collections.Generic.List<SoCrm.Services.Customers.Contracts.EMailAddress> emailAddresses);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/DeletePerson", ReplyAction="http://tempuri.org/ICustomerService/DeletePersonResponse")]
        void DeletePerson(SoCrm.Services.Customers.Contracts.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/DeleteEMailAddress", ReplyAction="http://tempuri.org/ICustomerService/DeleteEMailAddressResponse")]
        void DeleteEMailAddress(SoCrm.Services.Customers.Contracts.EMailAddress emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/DeletePhoneNumber", ReplyAction="http://tempuri.org/ICustomerService/DeletePhoneNumberResponse")]
        void DeletePhoneNumber(SoCrm.Services.Customers.Contracts.PhoneNumber phoneNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : SoCrm.Presentation.Customers.Customer.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<SoCrm.Presentation.Customers.Customer.ICustomerService>, SoCrm.Presentation.Customers.Customer.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<SoCrm.Services.Customers.Contracts.Person> GetAllPersons() {
            return base.Channel.GetAllPersons();
        }
        
        public System.Collections.Generic.List<SoCrm.Services.Customers.Contracts.Company> GetAllCompanies() {
            return base.Channel.GetAllCompanies();
        }
        
        public System.Collections.Generic.List<string> GetAllCountries() {
            return base.Channel.GetAllCountries();
        }
        
        public System.Collections.Generic.List<SoCrm.Services.Customers.Contracts.EMailAddress> GetAllEMailAddresses() {
            return base.Channel.GetAllEMailAddresses();
        }
        
        public System.Collections.Generic.List<SoCrm.Services.Customers.Contracts.ContactType> GetContactTypes() {
            return base.Channel.GetContactTypes();
        }
        
        public System.Collections.Generic.List<SoCrm.Services.Customers.Contracts.PhoneNumber> GetAllPhoneNumbers() {
            return base.Channel.GetAllPhoneNumbers();
        }
        
        public SoCrm.Services.Customers.Contracts.Person GetPersonByObjectId(System.Guid objectId) {
            return base.Channel.GetPersonByObjectId(objectId);
        }
        
        public System.Collections.Generic.List<SoCrm.Services.Customers.Contracts.Person> GetPersonsByNameAndCompany(string personName, string companyName) {
            return base.Channel.GetPersonsByNameAndCompany(personName, companyName);
        }
        
        public System.Collections.Generic.List<SoCrm.Services.Customers.Contracts.Company> GetCompaniesByNameAndCountry(string name, string counrty) {
            return base.Channel.GetCompaniesByNameAndCountry(name, counrty);
        }
        
        public SoCrm.Services.Customers.Contracts.Company GetCompanyByObjectId(System.Guid objectId) {
            return base.Channel.GetCompanyByObjectId(objectId);
        }
        
        public SoCrm.Services.Customers.Contracts.PhoneNumber CreatePhoneNumber(string phoneNumber, SoCrm.Services.Customers.Contracts.ContactType contactType) {
            return base.Channel.CreatePhoneNumber(phoneNumber, contactType);
        }
        
        public SoCrm.Services.Customers.Contracts.EMailAddress CreateEmailAddress(string emailAddress, SoCrm.Services.Customers.Contracts.ContactType contactType) {
            return base.Channel.CreateEmailAddress(emailAddress, contactType);
        }
        
        public SoCrm.Services.Customers.Contracts.Company CreateCompany(string name, string addressLine, string zipCode, string city, string country, string website) {
            return base.Channel.CreateCompany(name, addressLine, zipCode, city, country, website);
        }
        
        public SoCrm.Services.Customers.Contracts.Person CreatePerson(string firstName, string lastName, SoCrm.Services.Customers.Contracts.Company employer, string addressLine, string zipCode, string city, string country, System.Collections.Generic.List<SoCrm.Services.Customers.Contracts.PhoneNumber> phoneNumbers, System.Collections.Generic.List<SoCrm.Services.Customers.Contracts.EMailAddress> emailAddresses) {
            return base.Channel.CreatePerson(firstName, lastName, employer, addressLine, zipCode, city, country, phoneNumbers, emailAddresses);
        }
        
        public void DeletePerson(SoCrm.Services.Customers.Contracts.Person person) {
            base.Channel.DeletePerson(person);
        }
        
        public void DeleteEMailAddress(SoCrm.Services.Customers.Contracts.EMailAddress emailAddress) {
            base.Channel.DeleteEMailAddress(emailAddress);
        }
        
        public void DeletePhoneNumber(SoCrm.Services.Customers.Contracts.PhoneNumber phoneNumber) {
            base.Channel.DeletePhoneNumber(phoneNumber);
        }
    }
}
