//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoCrm.Services.Customers.Provider.AddressPersistence {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddressPersistence.IPersistenceServiceOf_Address")]
    public interface IPersistenceServiceOf_Address {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersistenceServiceOf_Address/Save", ReplyAction="http://tempuri.org/IPersistenceServiceOf_Address/SaveResponse")]
        System.Guid Save(SoCrm.Services.Customers.Contracts.Address entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersistenceServiceOf_Address/Get", ReplyAction="http://tempuri.org/IPersistenceServiceOf_Address/GetResponse")]
        SoCrm.Services.Customers.Contracts.Address Get(System.Guid objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersistenceServiceOf_Address/GetAll", ReplyAction="http://tempuri.org/IPersistenceServiceOf_Address/GetAllResponse")]
        System.Collections.Generic.List<SoCrm.Services.Customers.Contracts.Address> GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersistenceServiceOf_Address/Remove", ReplyAction="http://tempuri.org/IPersistenceServiceOf_Address/RemoveResponse")]
        void Remove(SoCrm.Services.Customers.Contracts.Address entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersistenceServiceOf_AddressChannel : SoCrm.Services.Customers.Provider.AddressPersistence.IPersistenceServiceOf_Address, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersistenceServiceOf_AddressClient : System.ServiceModel.ClientBase<SoCrm.Services.Customers.Provider.AddressPersistence.IPersistenceServiceOf_Address>, SoCrm.Services.Customers.Provider.AddressPersistence.IPersistenceServiceOf_Address {
        
        public PersistenceServiceOf_AddressClient() {
        }
        
        public PersistenceServiceOf_AddressClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersistenceServiceOf_AddressClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersistenceServiceOf_AddressClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersistenceServiceOf_AddressClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid Save(SoCrm.Services.Customers.Contracts.Address entity) {
            return base.Channel.Save(entity);
        }
        
        public SoCrm.Services.Customers.Contracts.Address Get(System.Guid objectId) {
            return base.Channel.Get(objectId);
        }
        
        public System.Collections.Generic.List<SoCrm.Services.Customers.Contracts.Address> GetAll() {
            return base.Channel.GetAll();
        }
        
        public void Remove(SoCrm.Services.Customers.Contracts.Address entity) {
            base.Channel.Remove(entity);
        }
    }
}
